### ISSUE TITLE
Fails to compile with python3.8

### ISSUE THREAD

**Issue by h-larsson** [primme/primme#30]
Hi,
using ``` make python  CC="gcc"```
I get tons of errors similar to 
```
primme.c:353:11: error: too many arguments to function ‘PyCode_New’
  353 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |           ^~~~~~~~~~
primme.c:57056:15: note: in expansion of macro ‘__Pyx_PyCode_New’
57056 |     py_code = __Pyx_PyCode_New(
      |               ^~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/compile.h:5,
                 from /usr/include/python3.8/Python.h:138,
                 from primme.c:39:
/usr/include/python3.8/code.h:122:28: note: declared here
  122 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
      |                            ^~~~~~~~~~

```

I use gcc 9.2.0 and python 3.8.1

**Comment by eromero-vlc** [comment]
The provided Python/primme.c was generated with an old version of cython. I was able to fix the issue by regenerating the file. I have uploaded a new version into master branch.

Also, you can regenerate that file on your own if you want. First, install the latest cython `pip install cython`, and then remove Python/primme.c. Now `make python` should work.

**Comment by h-larsson** [comment]
Thanks, it worked after adding ```-fPIC``` to ```$CFLAGS```

**Comment by eromero-vlc** [comment]
Glad to help!
